### PR TITLE
add close button

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change

Add close button to top right of panel

image

### Benefits
easily close the panel

### CODE REVIEW

**Comment by UziTech** [comment]
@50Wliu can I get this reviewed?

**Comment by 50Wliu** [comment]
I've been wondering for a while if this would make more sense as a dock.  If so then the close button will be automatically included.

**Comment by UziTech** [comment]
I was thinking that too. It would be nice to be able to move it from the right side.

**Comment by UziTech** [comment]
closing in favor of #58

**Pull request closed without merging**
