### PR TITLE
Added a clippy to the list to copyKeybindings

### LINKED ISSUE #30: Add ability to copy command name to clipboard
I was worried about getting the order of the transform keys wrong, e.g. `ctrl-shift` rather than `shift-ctrl`, so I thought I'd let atom resolve it and copy paste from there. But It's impossible to select the text. If it were, I don't know what would happen when I press `cmd-c`, of course...

Repro:
1. `key-binding-resolver:toggle`
2. press a key
3.Try to select that key as printed by the resolver

### PR DESCRIPTION
**Pull request by bdowling**
Similar to the keybindings list in settings-view, the clippy copies the binding
for easier editing / keymap customizations

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

This is a simple change to add a 'clippy' icon to allow the keybindings to be copied.  This is the same code from the settings-view on keybindings.

*Edit by @rsese to add the [screenshots](https://github.com/atom/keybinding-resolver/pull/62#issuecomment-415133553)*

keybinding-screenshot
keybinding-screenshot-atom-dark

### Benefits

This makes it so much easier to customize your keybindings by finding where the conflicts exist and overriding them in your local keymap.

### Possible Drawbacks

People spend all day customizing their keymaps.

### Applicable Issues

Looks like can close #34 which was written some time ago with similar intent, but this ain't coffee anymore ;)

Closes #30 
Closes #34

### CODE REVIEW

**Comment by rsese** [comment]
Thanks for contributing!  Can you add a screenshot that shows where the icon will be added?

**Comment by bdowling** [comment]
Can we try to get #58 merged too and I'll update the docs/images to show both UI changes? ;)

**Comment by bdowling** [comment]
keybinding-screenshot
keybinding-screenshot-atom-dark

**Comment by rsese** [comment]
> Can we try to get #58 merged too and I'll update the docs/images to show both UI changes? ;)

Sorry missed your comment here - it looks like you already dropped a comment in #58 and Winston will drop an update if he can, it seems like there was something else he wanted to look at based on his last comment.  I can go ahead and ask the team to take a look at this PR on its own for now.

And thanks for dropping those screenshots :+1:  I added them to the issue body.

**Comment by bdowling** [comment]
fwiw, I've tried to resubmit a couple times this pass to clear the flaky CI error, #60, but it does not appear to be working for Travis.  I don't believe I have anything that affects that here, but I've been wrong before.

**Comment by daviwil** [comment]
Thanks a lot for your contribution @bdowling! :sparkles:

**Pull request merged**
